### ISSUE TITLE
Multi stage build Dockerfile for GraalVM native compilation

### ISSUE THREAD

**Issue by cypressious** [spring-projects-experimental/spring-fu#115]
Please consider providing a Dockerfile for a multi stage build with GraalVM native compilation. The stages should be building the project (e.g. with Gradle), native compilation with GraalVM and the last step should be `FROM SCRATCH` where the native image is executed.

**Comment by dsyer** [comment]
Here's an example: https://github.com/dsyer/spring-boot-micro-apps/blob/f11487fcb64f88c84b488d4902de741bc0e73e7a/Dockerfile. The last stage can't be `FROM SCRATCH` because the binary created by `native-image` is not statically linked.

**Comment by cypressious** [comment]
@dsyer In the example at https://javalin.io/2018/09/27/javalin-graalvm-example.html, a static image is built with the `--static` flag and the final stage is `FROM scratch`. Can we apply this, too?

**Comment by sdeleuze** [comment]
`FROM scratch` indeed works, we are going to add a GraalVM native sample as part of #37 planned for the upcoming 0.4.0 milestone. See also https://github.com/spring-projects-experimental/spring-graalvm-native#use-docker-based-build-environment for GraalVM native dev oriented Docker image.
