### ISSUE TITLE
Add Micrometer support

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects-experimental/spring-fu#12]

**Comment by checketts** [comment]
I'm interested in helping. Are we looking at making it easy to configure micrometer, or to time specific items?

**Comment by sdeleuze** [comment]
Glad to accept your help on that one, especially since I am not a Micrometer guru ;-) Since I am in the process of updating Spring Fu to leverage [Spring Boot 2.1 infrastructure](https://github.com/spring-projects/spring-fu/issues?q=is%3Aissue+is%3Aopen+label%3A%22spring+boot+infra%22), I think this issue is more about making it easy to configure Micrometer via a Kotlin DSL.

**Comment by dragneelfps** [comment]
Is anyone working on this?

**Comment by sdeleuze** [comment]
I don't think anybody is working on this yet, and yeah I guess it should be handled as part of actuator support so I close this one to focus on #13.
