### ISSUE TITLE
Support GraalVM native images without custom configuration

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects-experimental/spring-fu#146]
See related GraalVM issues:
- [SubstrateVM should be able to analyze Spring functional bean definitions](https://github.com/oracle/graal/issues/905)
- [SubstrateVM breaks spring-jcl classpath detection](https://github.com/oracle/graal/issues/904)
- [java.util.logging not working in native image](https://github.com/oracle/graal/issues/728)
- [Logback requires a lot of configuration to work with SubstrateVM](https://github.com/oracle/graal/issues/807)
- [Log4j2 is broken with SubstrateVM](https://github.com/oracle/graal/issues/808)

On Spring Fu side, the main blocker is /META-INF/spring.factories (see #133).

**Comment by sdeleuze** [comment]
This issue should leverage the https://github.com/spring-projects/spring-framework/issues/22968 dedicated issue.

**Comment by sdeleuze** [comment]
We should leverage https://github.com/spring-projects-experimental/spring-graal-native-image (does not work yet but it should not be very far).

**Comment by SpiReCZ** [comment]
> We should leverage https://github.com/spring-projects-experimental/spring-graal-native-image (does not work yet but it should not be very far).

That is a great idea. 

Maybe also think about how Quarkus done it's features for native image compilation.

Spring has to be able to ease up native image compilation if it wants to be competitive in future cloud native development.

**Comment by sdeleuze** [comment]
Works now out of the box (at least for basic samples) with #269 and `spring-graal-native` `0.7-BUILD-SNAPSHOT` (using `functional` mode). Documentation and sample are coming with upcoming `spring-graal-native` `0.7` milestone.
