### ISSUE TITLE
Introduce a security { } DSL

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects-experimental/spring-fu#16]
Introduce a functional configuration equivalent for [`@EnableWebFluxSecurity`](https://docs.spring.io/spring-security/site/docs/5.0.5.RELEASE/reference/htmlsingle/#explicit-webflux-security-configuration).

**Comment by sdeleuze** [comment]
See related https://github.com/spring-projects/spring-security/issues/6624 issue.

**Comment by sdeleuze** [comment]
https://github.com/spring-projects/spring-security/issues/6624 has been fixed via [this commit ](https://github.com/spring-projects/spring-security/commit/5aacd0c9550e87360fde3ddd71f02c6d0029ff4f), so we should be able to move forward to support Spring Security DSL.

**Comment by sdeleuze** [comment]
@jonasbark has proposed to contribute on that issue (if he manages to find the time to work on it)

**Comment by sdeleuze** [comment]
Based on https://docs.spring.io/spring-security/site/docs/current/reference/html5/#kotlin-config

**Comment by skivol** [comment]
Need some security in my reactive "spring-fu" application :)
Will try to figure out how to translate @EnableWebFluxSecurity into dsl 👍

**Comment by sdeleuze** [comment]
Replaced by #319.
