### ISSUE TITLE
Add support for JOOQ

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects-experimental/spring-fu#220]

**Comment by davinkevin** [comment]
I would like to contribute on this one if possible / still relevant ? 

I've seen the new "way of doing" of the project with automatic transformation from annotation to functional definition, but if I can help on this specific subject, I will be pleased. 

JOOQ already contains all required information/object for configuration, so I think this could be straightforward…

FYI, some feature are still not yet supported for the graalvm compilation on the JOOQ side: https://github.com/jOOQ/jOOQ/issues/8779

**Comment by sdeleuze** [comment]
@davinkevin Hey, given the fact that JPA is really far from Spring Fu spirit I am open to extra focus on jOOQ support even if GraalVM native support is not yet ready.

We should leverage https://github.com/spring-projects-experimental/spring-init/ in 0.6 for automatic conversion, but nothing prevent moving forward by creating manually the initializers for now in the `autoconfigure-adapter` module if you want to contribute that along the DSLs.
