### ISSUE TITLE
Request Form-Data issue

### ISSUE THREAD

**Issue by halimpuckjava** [spring-projects-experimental/spring-fu#237]
hi

this a snapshot of my code to retrieve form-data

1.
```
coRouter {
    GET("/form") { it.awaitFormData().forEach { field, value -> log.info(.....); ok().buidAndWait() }
}
and even if i add contentType(MediaType.APPLICATION/MULTIPART-FORM-DATA) to GET
```
i see this exception : 
java.lang.IllegalStateException: No multipart HttpMessageReader !!!!!!!

2. whats the purpose to use ```form()``` & ```multipart()``` in codec dsl ??

**Comment by eanekrasov** [comment]
Try to add `multipart()` into `codecs` section of your configuration

**Comment by halimpuckjava** [comment]
i will try it but why add to codec ?? form & mutipart its just media type of http request

**Comment by halimpuckjava** [comment]
does't work, same exception

**Comment by eanekrasov** [comment]
Which enctype did you set for form?
`form()` codec and `awaitFormData()` works fine for forms with enctype `application/x-www-form-urlencoded` (default one)

**Comment by halimpuckjava** [comment]
yes you are right but i want to use it with header: form-data

**Comment by sdeleuze** [comment]
Please provide a repro project based on 0.3.0.
