### ISSUE TITLE
Spring Kofu Download files issue 

### ISSUE THREAD

**Issue by halimpuckjava** [spring-projects-experimental/spring-fu#238]
hi

```
coRouter {
     GET("/download") {
          val input = ClasspathResource("...").inputStream
          ok().headers { ...... }.bodyAndAwait(input) 
     }
}
```

exception appear: 
```
com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No serializer found for class java.io.BufferedInputStream and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS)
```

if i disable feature' FAIL_ON_EMPTY_BEANS' in jackson dsl it work but the the content of input is empty (file downloaded empty)

**Comment by eanekrasov** [comment]
Try to add `resource()` into `codecs` section

**Comment by halimpuckjava** [comment]
thanks

but still not work, issue is not for resource file or location but when serialize inputstram jackson failure, even if disable serialisation feature jackson can serialize inputstream but with empty content

**Comment by sdeleuze** [comment]
Please provide a repro project.

**Comment by sdeleuze** [comment]
I close it for now, please reopen if you provide a repro project.
