### ISSUE TITLE
Document that spring-fu does not support devtools restart logic yet

### ISSUE THREAD

**Issue by cebaa** [spring-projects-experimental/spring-fu#244]
Starting from [kofu-reactive-minimal](https://github.com/spring-projects/spring-fu/tree/master/samples/kofu-reactive-minimal) example and adding devtools to `build.gradle.kts`:

```
val developmentOnly by configurations.creating
configurations {
  runtimeClasspath {
    extendsFrom(developmentOnly)
  }
}

dependencies {
  ...
  developmentOnly("org.springframework.boot:spring-boot-devtools")
}
```

With this main app code restarts work fine:

```
@SpringBootApplication
class App {
  @Bean
  fun route() = router {
    GET("") { _ -> ok().body(fromObject("hello\n")) }
  }
}

fun main(args: Array<String>) {
  SpringApplication.run(App::class.java, *args)
}
```

Changing to use spring-fu:

```
val app = application(WebApplicationType.REACTIVE) {
  webFlux {
    router {
      GET("") { _ -> ok().body(fromObject("hello\n")) }
    }
  }
}

fun main() {
  app.run()
}
```

stops restarts from happening.

I could not find a spring-fu + devtools example, so I'm not sure if anything else needs to be configured in addition to the above.

**Comment by sdeleuze** [comment]
Given the fact that Spring Fu applications starts pretty fast I admit Devtools support has not been tested, but since there are improvements expected in Spring Boot 2.4 on that topic, let's take the opportunity to fix what needs to be fixed since devtools also allows disabling caching for some resources etc.

**Comment by sdeleuze** [comment]
Not supported yet so I have documented that for now.
