### ISSUE TITLE
Allow externally defined KoFu DSLs

### ISSUE THREAD

**Issue by 0n3z** [spring-projects-experimental/spring-fu#253]
AbstractDsl initialize() is marked as internal. This prevents external sub classes to work properly. If the constraint is relaxed, it would allow external projects to provide their own applicative DSLs or side projects to add featured DSLs enabling fast community driven enrichment.

**Comment by sdeleuze** [comment]
Good point, I will change that as part of 0.3.

**Comment by sdeleuze** [comment]
I will then rollback #218 and make it `public` since `protected` does not allow the DSLs to initialize each others. Maybe #275 will allow extensibility while not exposing such "internal" method on the public API cc @poutsma.
