### ISSUE TITLE
Spring Kofu TransactionalOperator Support with R2DBC

### ISSUE THREAD

**Issue by halimpuckjava** [spring-projects-experimental/spring-fu#259]

**Comment by sdeleuze** [comment]
Duplicates of #129 which is already fixed.

**Comment by pull-vert** [comment]
@sdeleuze can you explain how to obtain TransactionalOperator with kofu please ?

Considering this article [reactive transactions with Spring](https://spring.io/blog/2019/05/16/reactive-transactions-with-spring) we should be able to inject and use a ```TransactionalOperator``` to mange transactional queries.
Kofu R2DBC for now just registers a ```DatabaseClient``` as a Bean in Spring Context.

For example this is the [H2 initializer code](https://github.com/spring-projects-experimental/spring-fu/blob/master/autoconfigure-adapter/src/main/java/org/springframework/boot/autoconfigure/data/r2dbc/H2DatabaseClientInitializer.java), Postgres and other R2DBC initializers are built on the same model.

Shouldn't the Initializers expose ```TransactionalOperator``` as well ?
```java
ConnectionFactory factory = …
ReactiveTransactionManager tm = new R2dbcTransactionManager(factory);

context.registerBean(DatabaseClient.class, () -> DatabaseClient.create(factory));
context.registerBean(TransactionalOperator.class, () -> TransactionalOperator.create(tm));
```
