### ISSUE TITLE
Production Evaluation

### ISSUE THREAD

**Issue by jeffzoch** [spring-projects-experimental/spring-fu#261]
Since everyone has a definition of production-readiness, i'd like to throw in my 2 cents on how my team would prefer to evaluate when we can switch:
If we could get a list of spring features that are supported / plan to be supported / will not be supported (maybe via checkboxes and strikethroughs) then it'd be easy for people to evaluate whether they are ready to use something like this. 

Personally I was looking for things like:
- metrics configurations
- @Scheduled annotation parity
- repository support

Even combing through the issues its not entirely clear whats covered.

**Comment by pull-vert** [comment]
I would like to have a temporal roadmap for a few additional items that seem important to me:
1. Spring security
2. Spring data-jdbc

I have the feeling that this project is almost dormant for quite some time, it is clearly less active than before while a lot of important features are still missing. Is spring-fu a Spring priority project ?

**Comment by AlexCzar** [comment]
@pull-vert spring-fu is a sandbox project, its main purpose is to test new ideas and approaches and play with kotlin APIs intended for future versions of Spring Boot, it is in no way intended for "real production".

**Comment by sdeleuze** [comment]
As explained in https://spring.io/blog/2020/05/28/spring-fu-0-3-0-and-beyond our focus is more on getting the architecture and APIs right before expanding the scope of the features supported, thanks to be patient ;-)
