### ISSUE TITLE
Spring Kofu Suggestions

### ISSUE THREAD

**Issue by halimpuckjava** [spring-projects-experimental/spring-fu#271]
hi

1. add CHANGE log for updates release

2. when spring kofu will be ready for production

3. documention for spring kofu + graalvm (native image)

**Comment by sdeleuze** [comment]
Hi,

1. I did not create change logs for 0.3.0 milestones on purpose but 0.3.0 is now available with a [changelog ](https://github.com/spring-projects-experimental/spring-fu/releases) and a related [blog post](https://spring.io/blog/2020/05/28/spring-fu-0-3-0-and-beyond).

2. No news to share about that but we have a focus on functional APIs and GraalVM native in Spring roadmap.

3. See https://github.com/spring-projects-experimental/spring-fu#native-images for samples, documentation should be available on [spring-graalvm-native](https://github.com/spring-projects-experimental/spring-graalvm-native) shortly.
