### ISSUE TITLE
Upgrade to leverage R2dbcProperties and official R2DBC Boot support

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects-experimental/spring-fu#274]
Use official configuration available as of Spring Boot 2.3 instead of manual configuration done currently. Likely to provide a unified `r2dbc` configuration block for all databases instead of current `r2dbcH2`/`r2dbcPostgresql`.

**Comment by sdeleuze** [comment]
We should check that `ConnectionFactory` is exposed as asked in #262.

See also https://github.com/spring-projects/spring-data-r2dbc/issues/378.

**Comment by pull-vert** [comment]
@aneveu @sdeleuze Hi and thanks for this nice feature. 

Considering this article [reactive transactions with Spring](https://spring.io/blog/2019/05/16/reactive-transactions-with-spring) we should use a ```TransactionalOperator``` to manage transactional queries.
New R2dbcInitializer only registers a ```DatabaseClient``` Bean in Spring Context.

Shouldn't R2dbcInitializer also register ```TransactionalOperator``` as Bean in Spring context, or maybe just expose the ```ConnectionFactory``` so we can create a ```TransactionalOperator``` from it like this ?

```java
ConnectionFactory factory = …
ReactiveTransactionManager tm = new R2dbcTransactionManager(factory);
TransactionalOperator to = TransactionalOperator.create(tm);
```

**Comment by aneveu** [comment]
> @aneveu @sdeleuze Hi and thanks for this nice feature.
> 
> Considering this article [reactive transactions with Spring](https://spring.io/blog/2019/05/16/reactive-transactions-with-spring) we should use a `TransactionalOperator` to manage transactional queries.
> New R2dbcInitializer only registers a `DatabaseClient` Bean in Spring Context.
> 
> Shouldn't R2dbcInitializer also register `TransactionalOperator` as Bean in Spring context, or maybe just expose the `ConnectionFactory` so we can create a `TransactionalOperator` from it like this ?
> 
> ```java
> ConnectionFactory factory = …
> ReactiveTransactionManager tm = new R2dbcTransactionManager(factory);
> TransactionalOperator to = TransactionalOperator.create(tm);
> ```

You're right, thanks for the suggestion! We're gonna add a boolean flag to let users enable the transactional mode and though retrieve the `TransactionalOperator`.

**Comment by pull-vert** [comment]
Thanks a lot @aneveu and @fteychene !
