### ISSUE TITLE
Upgrade to Spring Boot 2.4 M2

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects-experimental/spring-fu#277]

**Comment by pull-vert** [comment]
is it possible to release a spring-fu milestone based on [spring-boot 2.4.0-M1](https://spring.io/blog/2020/06/29/spring-boot-2-4-0-m1-is-now-available) please ?

**Comment by sdeleuze** [comment]
Sorry but we prefer wait for Spring Boot 2.4 M2.
