### ISSUE TITLE
Add in JaFu missing KoFu configurations

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects-experimental/spring-fu#278]
Such as Cassandra or Redis support.

**Comment by hamid646** [comment]
I'd be interested to do Cassandra one as Redis is in progress

**Comment by hamid646** [comment]
I added Cassandra changes with a sample app https://github.com/spring-projects-experimental/spring-fu/pull

**Comment by sdeleuze** [comment]
This will be replaced by more specific issues.

@hamid646 I will review your PR shortly.
