### ISSUE TITLE
How does one run spring-fu without WebServer?

### ISSUE THREAD

**Issue by WithoutCaps** [spring-projects-experimental/spring-fu#285]
How does one run spring-fu without WebServer? If I replace `reactiveWebApplication` DSL with `application` DSL - application exits immediately after initialization

**Comment by WithoutCaps** [comment]
I did a little bit of digging through old commits and I found this:
![image](https://user-images.githubusercontent.com/23264966/84671932-9cab8980-af30-11ea-8ffb-c105fe94cc60.png)
I guess this feature is not supported anymore...
I'll probably do the same, tho maybe ill use thread lock instead

**Comment by AlexCzar** [comment]
You could probably use something like a `CountDownLatch`.
