### ISSUE TITLE
Add default resource with static content

### ISSUE THREAD

**Issue by halimpuckjava** [spring-projects-experimental/spring-fu#298]
hi

add default resource with static content
```
   defaultResource(path: String, resource: Resource)
```
its useful request url without specify any resource name (ex: HTTP://HOST:PORT  in this case and if index.html is present in resource its automatic loaded to client as default response)

**Comment by sdeleuze** [comment]
`resources("/**", ClassPathResource("static/"))` is already added for both WebFlux and WebMvc.
