### ISSUE TITLE
Upgrade to latest spring-data-r2dbc changes

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects-experimental/spring-fu#299]
When https://github.com/spring-projects/spring-data-r2dbc/tree/issue/gh-368 will be merged in order to take advantage of `spring-r2dbc` module from Spring Framework and of `R2dbcEntityOperations`.

**Comment by skivol** [comment]
I guess https://github.com/spring-projects/spring-data-r2dbc/pull/412 is the change in question (issue/gh-368 branch got deleted).
