### ISSUE TITLE
provide a way to use pure spring-r2dbc without spring-data-r2dbc dependency

### ISSUE THREAD

**Issue by pull-vert** [spring-projects-experimental/spring-fu#314]
Right now this is impossible because the last line of ```R2dbcDsl``` requires spring-data-r2dbc dependency or else throws some java.lang.NoClassDefFoundError (for example on org/springframework/data/r2dbc/core/R2dbcEntityTemplate).

```java
override fun initialize(context: GenericApplicationContext) {
    super.initialize(context)
    init()

    val properties = r2dbcProperties()

    R2dbcInitializer(properties, optionsCustomizers, transactional).initialize(context)
    R2dbcDataInitializer().initialize(context)
}
```

**Comment by gytis-ivaskevicius** [comment]
Actually this is a great idea, and may i add that https://github.com/JetBrains/Exposed is going to be getting r2dbc support in near future which means that r2dbc context could be reused for both

**Comment by sdeleuze** [comment]
@pull-vert `spring-r2dbc` is very low level and the new `spring-data-r2dbc` that leverage it pretty lightweight, what is your use case for it?

@gytis-ivaskevicius Initializers are distincts so we should be able to use `R2dbcInitializer` in a potential Exposed support.

**Comment by pull-vert** [comment]
@sdeleuze the use case I have is visible in my [sample](https://github.com/ufoss-org/kotysa/blob/master/samples/kotysa-reactive-r2dbc) that is using kofu together with [kotysa-spring-r2dbc](https://github.com/ufoss-org/kotysa/tree/master/kotysa-spring-r2dbc).

I needed to add spring-data-r2dbc dependency so I can use kofu's ```r2dbc``` DSL for the reason I explained, whereas spring-r2dbc should be sufficient for my [kotysa-spring-r2dbc](https://github.com/ufoss-org/kotysa/tree/master/kotysa-spring-r2dbc) use.

**Comment by sdeleuze** [comment]
Yeah good point, I guess we should put Spring Data config in a dedicated namespace with `data { r2dbc { } }` or `dataR2dbc { }`, same for JDBC.

**Comment by fteychene** [comment]
I drafted a PR #342 with a design of dsl to separate r2dbc and spring-data r2dbc.
If it's okay for this design I will add afu one in the PR to be merged
