### ISSUE TITLE
Using 'reactiveWebApplication' with 'ServletHttpHandlerAdapter' to deploy as 'WAR'

### ISSUE THREAD

**Issue by borag** [spring-projects-experimental/spring-fu#320]
Hi, is there a simple way to use Kofu 'reactiveWebApplication' to be deployed as a 'WAR' file ?
I hacked a little bit and registered
- ServletHttpHandlerAdapter
- WebHttpHandlerBuilder
- 'webHandler' routes

But not happy with dsl's.
I know it's not recommended to deploy as 'WAR' file but customer is always right :)

**Comment by sdeleuze** [comment]
I don't think I have the bandwidth to handle that but I will review PR if you can craft it.

**Comment by sdeleuze** [comment]
I think that's best to close this issue since I am not sure this is a use case we will support.
