### ISSUE TITLE
Add JDBC support for non embedded datasources

### ISSUE THREAD

**Issue by vladimirfx** [spring-projects-experimental/spring-fu#322]
Jdbc is usable in reactive projects for support workloads such as schema management (Liquibase https://liquibase.jira.com/browse/CORE-3419) or Quartz clustered scheduler.

**Comment by sdeleuze** [comment]
I am not sure about the purpose of this issue, what would you like to be fixed/supported?

**Comment by vladimirfx** [comment]
IMO JDBC DSL should provide ability to connect to external (Non-embedded) database. Currently only EmbeddedDataSourceConfigurationInitializer is used in DSL:
https://github.com/spring-projects-experimental/spring-fu/blob/d80a9d090f0a24f4f41cf757702a34a3f9d4a12d/kofu/src/main/kotlin/org/springframework/fu/kofu/jdbc/JdbcDsl.kt#L45

Other Datasource configurators (like DataSourceConfiguration_GenericInitializer) is present in autoconfigure-adapter subproject but not used in DSLs. Or I am missing something?

**Comment by sdeleuze** [comment]
Fix for KoFu via #332, JaFu support will come via #339 in 0.5.0 as well as refined support that we have started to discuss with @aneveu and @fteychene.
