### ISSUE TITLE
Is the conceptual decision to abandon Spring Boot configuration infrastructure?

### ISSUE THREAD

**Issue by vladimirfx** [spring-projects-experimental/spring-fu#323]
Currently all DSLs create new *Properties objects without ability to override/customize/provide configuration information. Is the conceptually new way to provide configuration or temporal implementation in current phase of project?

**Comment by sdeleuze** [comment]
This is temporary, see related #318. Could you elaborate on the need you have?

**Comment by vladimirfx** [comment]
Thanks, where we can discuss use cases?

**Comment by sdeleuze** [comment]
In #318 if you feel it is relevant enough.
