### ISSUE TITLE
Spring native image with Spring Fu Kotlin DSL

### ISSUE THREAD

**Issue by halimpuckjava** [spring-projects-experimental/spring-fu#328]
hi @sdeleuze 

i love spring kofu with kotlin dsl, so i ask if spring native image support fu kotlin dsl ? if yes i hope to make some documenttaion about it, if no when we expected to see spring kofu native image

**Comment by sdeleuze** [comment]
Hi, you can see a complete example in https://github.com/spring-projects-experimental/spring-fu/tree/master/samples/kofu-petclinic-jdbc, we will document that as part of #315.
