### ISSUE TITLE
KoFu: Allow sharing bean definitions with a @SpringBootApplication

### ISSUE THREAD

**Issue by sgybas** [spring-projects-experimental/spring-fu#335]
We are using a traditional `@SpringBootApplication` for production and would like to use KoFu for integration tests. We expect faster tests and would like to learn KoFu already until it is ready for production.

For this, we like to share our bean definitions

```koltin
val moduleBeans = beans {
    bean<MyHandler>()
    bean<MyService>()
    bean(::routes)
}
```

between production

```kotlin
@SpringBootApplication
class MyApplication

fun main() {
    runApplication<MyApplication> {
        addInitializers(moduleBeans)
    }
}
```

and the KoFu app for integration tests

```kotlin
val app = reactiveWebApplication {
    webFlux {
        [...]
    }

    // we would like to include moduleBeans here without code duplication
}
```

We have found only one way to make sharing the stand-alone bean definitions work:

```kotlin
fun BeanDefinitionDsl.moduleBeans() {
    bean<MyHandler>()
    bean<MyService>()
    bean(::routes)
}
```

```kotlin
fun main() {
    runApplication<MyApplication> {
        addInitializers(beans { moduleBeans() })
    }
}
```

and in the DSL

```kotlin
val app = reactiveWebApplication {
    webFlux {
        [...]
    }

    beans {
        moduleBeans()
    }
}
```

That's not very elegant. Did we miss something? If not, how about adding

```kotlin
fun enable(beans: BeanDefinitionDsl) {
    beans.initialize(context)
}
```

or even

```kotlin
fun enable(beans: ApplicationContextInitializer<in GenericApplicationContext>) {
    beans.initialize(context)
}

```

to `ConfigurationDsl` so we can simply enable the bean definition

```kotlin
val app = reactiveWebApplication {
    webFlux {
        [...]
    }

    enable(moduleBeans)
}
```

? This also allows a step-by-step migration from a `SpringBootApplication` by starting with programmatic bean registration.

**Comment by cheroliv** [comment]
Hi, the idea to give a path to migrate is good.
Or at least I would like to see how to enable annotation base package scanning.
That will allow to keep the part of the bean configuration who is no ready to be 100% dsl written without having to extend classes like WebSecurityConfigurerAdapter.

**Comment by fteychene** [comment]
I agree that we should add this `enable` in Kofu `ConfigurationDsl` since it's available in Jafu.
