### ISSUE TITLE
Have any plan to support armeria?

### ISSUE THREAD

**Issue by wickedev** [spring-projects-experimental/spring-fu#351]
Have any plan to support armeria that creating framework by creator of Netty? Armeria using own engine like jetty or undertow. or remove the `@PublishedApi internal` declaration on the `context` property of `AbstractDsl` for power users can easily customize it.

https://github.com/line/armeria

```kt
/* Example */
import com.linecorp.armeria.spring.web.reactive.ArmeriaReactiveWebServerFactory
import org.springframework.boot.web.reactive.error.ErrorWebExceptionHandler

val app = reactiveWebApplication {
    webFlux {
        armeria()
    }
    excludes(ErrorWebExceptionHandler::class)
}

fun WebFluxServerDsl.armeria() {
    engine = ArmeriaReactiveWebServerFactory(context.beanFactory, env)
}

fun <T : Any> AbstractDsl.excludes(vararg clazz: KClass<T>) {
    clazz.forEach {
        this.context.removeBeanDefinition(it.java.name)
    }
}
```

**Comment by sdeleuze** [comment]
Not for now since our focus is on Spring Boot scope, but our WIP extensibility model should enable Armeria to provide such support externally.
