### ISSUE TITLE
Question: Overview of "finished" features/use cases for developers

### ISSUE THREAD

**Issue by bennettdams** [spring-projects-experimental/spring-fu#352]
As a long-time Spring user with growing dislike of its "magic", I'm really looking forward to using KoFu and explicit application configuration.

I think it would be nice to have a prominent overview of already "finished" features, e.g. at the root README, but catered towards **developers who are using Spring**, instead of Spring developers.

Here's a simple use case, I want to have an application with

- Authentication/authorization
- MongoDB connection
- GraphQL endpoints

...but right now there's no easy way of finding out out which of the underlying technologies are ready to be used.

I understand that there are many topics to be worked on for KoFu that it's not considered "production ready", but there's also a lot of work done that could be used/tested in real life projects by "users".
At least for me, an overview of real life use cases (like above) and their status (e.g. "you can use it", "watch out when using it", "not recommended to use") would be really nice.

**Comment by sdeleuze** [comment]
We will give more information via #381.
