### ISSUE TITLE
Project timeline

### ISSUE THREAD

**Issue by migroskub** [spring-projects-experimental/spring-fu#387]
I see that this project is incubating for more than a year. Is there any timeline for making it official and getting out of the experimental stage?

**Comment by EndzeitBegins** [comment]
Unfortunately I don't think there is, see #381.

Based on the focus on Spring Native, I assume that Spring Fu may only become stable after release of Spring 6.0 and Spring Boot 3.0 respectively.
But that is just a personal speculation.

**Comment by sdeleuze** [comment]
For now, indeed not much to add than what I shared in #381 indeed, we will communicate here and on Twitter with more information later, thanks for your understanding.
